Editar conta
Is-It-Safe/mobile pull request #102
Opened 2023-01-09 20:39 UTC by Endleyson

tentando enviar as modificações corretas pela terceira vez

2023-01-09 20:44 UTC, estermabel requested changes

2023-01-09 20:44 UTC, estermabel commented on lib/src/app/modules/configuration/account/presenter/pages/edit_account_page.dart
> +                // const SizedBox(height: 16),
Pq ta comentado??

2023-01-09 20:44 UTC, estermabel commented on lib/src/app/modules/configuration/account/presenter/pages/edit_account_page.dart
> +                    // validator: (value) => controller.validateTextField(value),
Pq ta comentado??

2023-01-09 20:44 UTC, estermabel commented on lib/src/app/modules/configuration/account/presenter/pages/edit_account_page.dart
> +                      // validator: (value) => controller.validateTextField(value),
Pq ta comentado??

2023-01-09 20:44 UTC, estermabel commented on lib/src/app/modules/configuration/account/presenter/pages/edit_account_page.dart
> +                    // validator: (value) => controller.validateTextField(value),
Pq ta comentado??

2023-01-09 20:44 UTC, estermabel commented on lib/src/app/modules/configuration/account/presenter/pages/edit_account_page.dart
> +              // controller.birthdateController.text = birthDate!;
Remover caso não utilizar

2023-01-09 20:44 UTC, estermabel commented on lib/src/app/modules/configuration/account/presenter/pages/edit_account_page.dart
> +                    // validator: (value) => controller.validateBirthdate(value),
Pq ta comentado??

2023-01-10 12:46 UTC, Endleyson commented on lib/src/app/modules/configuration/account/presenter/pages/edit_account_page.dart
> +                    // validator: (value) => controller.validateBirthdate(value),
esqueci de descomentar

2023-01-10 12:47 UTC, Endleyson commented on lib/src/app/modules/configuration/account/presenter/pages/edit_account_page.dart
> +              // controller.birthdateController.text = birthDate!;
removido

2023-01-10 12:53 UTC, estermabel approved these changes

2023-01-10 12:53 UTC, merged