bug: ajuste do scrollbar de experiência do usuário
Is-It-Safe/mobile pull request #138
Opened 2023-03-02 00:11 UTC by hastnumber1

Scrollbar com texto de acordo com o solicitado

2023-03-02 02:41 UTC, feliperfdev commented
Favor, olhar comentários deixados por mim no arquivo referente ao **AuthService**, presente no commit.

2023-03-02 20:33 UTC, feliperfdev requested changes

2023-03-04 18:55 UTC, hastnumber1 commented on lib/src/service/api/modules/auth/auth_service.dart
> +        password: '123456',
Alteração realizada

2023-03-04 20:53 UTC, devlucasandrade commented
Conforme conversamos, ajusta no componente os nomes, de acordo com a informação do Figma - https://www.figma.com/file/MjdUrdDe6Bj44gnpq28f7d/Is-It-Safe%3F---App?node-id=9%3A2&t=mtEN3VeY9PrjU0bc-0
![image](https://user-images.githubusercontent.com/98838229/222928200-494f1ea6-7cf4-4931-af44-54cb39662f74.png)

2023-03-04 20:56 UTC, devlucasandrade commented on lib/l10n/intl_pt.arb
> -    "textNeutral":"Neutro",
Ajustar os textos conforme alinhamos, seguindo o que está no figma

2023-03-05 03:43 UTC, feliperfdev commented on lib/src/service/api/modules/auth/auth_service.dart
> +        password: '123456',
Lembrando aqui que não há problema algum em mockar os dados dos serviços para agilizar o processo ao longo do desenvolvimento de telas ou implementação de features. O que não pode é mandar o mock diretamente para a branch dev 😅.
O único caso em que isso é permitido, se aplica aos testes de unidade, pois é onde costumamos mockar os dados para trabalhar apenas com o conceito/comportamento dos casos de uso, sem nos importarmos com conexões reais entre os serviços com drivers externos e APIs.

2023-03-05 03:44 UTC, feliperfdev submitted a review, later dismissed

2023-03-05 12:34 UTC, hastnumber1 commented on lib/l10n/intl_pt.arb
> -    "textNeutral":"Neutro",
Correções realizadas

2023-03-05 20:34 UTC, feliperfdev submitted a review, later dismissed

2023-03-05 22:24 UTC, devlucasandrade requested changes

2023-03-05 22:24 UTC, devlucasandrade commented on lib/src/app/modules/profile/presenter/widgets/profile_review/profile_review.dart
> -    if (grade >= 4.0) return AssetConstants.emoticon.excited;
Não era para remover o código, pois ele valida a nota dentro desses limites, para a partir daí apresentar o emoticon.
Nesse caso, teria que assim como no scroll, mudar apenas os nomes. As demais validações permanecem as mesmas.

2023-03-05 22:24 UTC, devlucasandrade commented on lib/src/app/modules/profile/presenter/widgets/profile_review/profile_review.dart
> -    if (grade >= 4.0) return S.current.textExcited;
Não era para remover o código, pois ele valida a nota dentro desses limites, para a partir daí apresentar o texto.
Nesse caso, teria que assim como no scroll, mudar apenas os nomes. As demais validações permanecem as mesmas.

2023-03-06 17:35 UTC, hastnumber1 commented on lib/src/app/modules/profile/presenter/widgets/profile_review/profile_review.dart
> -    if (grade >= 4.0) return AssetConstants.emoticon.excited;
resolvido

2023-03-07 17:34 UTC, devlucasandrade approved these changes

2023-03-07 17:35 UTC, merged