Bug/Layout de texto quebra quando aumenta a fonte no SO
Is-It-Safe/mobile pull request #141
Opened 2023-03-05 23:02 UTC by devlucasandrade

O layout estava quebrando os widgets quando era aumentada a fonte a partir do SO do aparelho. Ajustes realizados.
- Ajuste realizado para quando a nota do estabelecimento, quando a mesma for zero, não ser exibida.

2023-03-05 23:18 UTC, feliperfdev requested changes

2023-03-05 23:18 UTC, feliperfdev commented on lib/src/service/api/modules/auth/auth_service.dart
> +      password: '123456',
Mock está sendo enviado para a branch dev. Favor, retirar.

2023-03-06 01:51 UTC, devlucasandrade commented on lib/src/service/api/modules/auth/auth_service.dart
> +      password: '123456',
Ajustado.

2023-03-06 19:41 UTC, feliperfdev approved these changes

2023-03-07 01:31 UTC, merged