Feature/135 home exibir lugares próximos
Is-It-Safe/mobile pull request #213
Opened 2023-04-16 02:01 UTC by devlucasandrade

Funcionando, mas com ressalvas.
Será aberto uma Issue para correção dos bugs encontrados.

2023-04-18 12:28 UTC, estermabel requested changes

2023-04-18 12:28 UTC, estermabel commented on lib/src/app/modules/home/presenter/bloc/home_bloc.dart
> +          '''User denied permissions to access the device's location.''') {
Adicionar texto no arquivo intl

2023-04-18 12:28 UTC, estermabel commented on lib/src/app/modules/home/presenter/bloc/home_bloc.dart
> +          'The location service on the device is disabled.') {
Adicionar texto no arquivo intl

2023-04-18 12:28 UTC, estermabel commented on lib/src/app/modules/home/presenter/bloc/home_bloc.dart
> +    }).timeout(const Duration(seconds: 3000), onTimeout: () async {
esse 3000 poderia ficar em algum arquivo de constantes. E não acha que 50min é um tempo muito grande para timeout??

2023-04-18 12:28 UTC, estermabel commented on lib/src/app/modules/home/presenter/widgets/home_location_card.dart
> +          grade == '0.0' ? StringConstants.empty : grade,
'0.0' adicionar em algum arquivo de StringConstants.

2023-04-18 21:30 UTC, devlucasandrade commented on lib/src/app/modules/home/presenter/widgets/home_location_card.dart
> +          grade == '0.0' ? StringConstants.empty : grade,
Adicionado como StringConstants.zeroAvaliation

2023-04-24 10:08 UTC, estermabel approved these changes

2023-04-24 10:08 UTC, merged