308 bug add location criar validação e mensagem para cep inválido na tela adicionar local
Is-It-Safe/mobile pull request #369
Opened 2023-10-24 18:46 UTC by flaviomelodev

### O que foi feito? 
Agora está retornando quando o CEP é inválido da chamada da API

Quando for um CEP inválido retorna mensagem de erro

### Tipo de Mudança:

[x] feature 

### Validações:

#### Testes Unitários:

- [X] Meu código possui os devidos testes unitários

#### Layout:

- [X] Necessita de validação de Design

### Screenshots

2023-10-24 18:55 UTC, eusoumabel requested changes

2023-10-24 18:55 UTC, eusoumabel commented on lib/src/app/modules/location/presenter/bloc/save_location_bloc.dart
> +    return errorMessage ?? '';
StringConstants.empty

2023-10-24 18:55 UTC, eusoumabel commented on test/app/modules/location_module/domain/usecases/get_location_by_cep_use_case_test.dart
> +  });
Faltou os testes de erro

2023-10-25 11:32 UTC, flaviomelodev commented on lib/src/app/modules/location/presenter/bloc/save_location_bloc.dart
> +    return errorMessage ?? '';
feito

2023-10-25 11:32 UTC, flaviomelodev commented on test/app/modules/location_module/domain/usecases/get_location_by_cep_use_case_test.dart
> +  });
feito

2023-10-25 12:01 UTC, eusoumabel submitted a review, later dismissed

2023-10-25 13:30 UTC, eusoumabel approved these changes

2023-10-25 16:18 UTC, eusoumabel approved these changes

2023-10-28 10:41 UTC, eusoumabel requested changes
O tipo ideal seria: Future<Result<Request...>>

2023-10-28 10:41 UTC, eusoumabel commented on .vscode/launch.json
> +        "flutterMode": "release",
Seria melhor só colocar essa linha caso for testar em release mode. No default, melhor deixar debug para a gnt conseguir mapear algumas situações melhor

2023-10-30 22:00 UTC, eusoumabel approved these changes

2023-10-31 13:26 UTC, merged