botão de cadastrar só habilita com os dados e termos aceitos
Is-It-Safe/mobile pull request #420
Opened 2024-01-21 02:16 UTC by flaviomelodev

### O que foi feito? 
Habilitado botão de CADASTRAR com dados preenchidos e aceite dos termos

### Tipo de Mudança:

Uploading aceite de termos.mov…

[x] bug

### Validações:

#### Testes Unitários:

- [ ] Meu código possui os devidos testes unitários

#### Layout:

- [ ] Não houveram mudanças nas telas
- [ ] Necessita de validação de Design

### Screenshots

2024-01-21 17:19 UTC, eusoumabel requested changes

2024-01-21 17:19 UTC, eusoumabel commented on lib/src/app/modules/auth/modules/register/presenter/pages/register_page.dart
> +                            if (bloc.store.isRegisterButtonEnabled.data == true && bloc.store.isTermsAndConditionsChecked.data == true) {
Essa regra de negócio deveria estar dentro do bloc, e não na page.

2024-01-23 14:50 UTC, flaviomelodev commented on lib/src/app/modules/auth/modules/register/presenter/pages/register_page.dart
> +                            if (bloc.store.isRegisterButtonEnabled.data == true && bloc.store.isTermsAndConditionsChecked.data == true) {
Coloquei a regra dentro do bloc

2024-01-23 17:34 UTC, eusoumabel commented on lib/src/app/modules/auth/modules/register/presenter/bloc/register_bloc.dart
> +    }
Sugestão:

`return (store.isRegisterButtonEnabled.data && store.isTermsAndConditionsChecked.data)`

2024-01-23 17:34 UTC, eusoumabel approved these changes

2024-01-23 17:34 UTC, eusoumabel approved these changes

2024-01-23 17:34 UTC, merged