Ajustar feedback após cadastro de local
Is-It-Safe/mobile pull request #434
Opened 2024-02-11 00:54 UTC by AdrianaBispo

### O que foi feito? 

### Tipo de Mudança:

### Validações:

#### Testes Unitários:

- [ ] Meu código possui os devidos testes unitários

#### Layout:

- [ ] Não houveram mudanças nas telas
- [ ] Necessita de validação de Design

### Screenshots

2024-02-15 23:29 UTC, eusoumabel requested changes

2024-02-15 23:29 UTC, eusoumabel commented on lib/src/app/modules/location/presenter/bloc/save_location_bloc.dart
> +          var locationModular = Modular.get<SafeStream<LocationEntity?>>();
Pq essa variável local?? ela ta sendo utilizada em algum outro lugar??

2024-02-17 15:37 UTC, AdrianaBispo commented on lib/src/app/modules/location/presenter/bloc/save_location_bloc.dart
> +          var locationModular = Modular.get<SafeStream<LocationEntity?>>();
Ela está mudando o valor do atributo 'data' para 'success' para que no arquivo save_location_page.dart possa ser mostrado o SuccessSnackBar. Pois quando 'location.data != null' aparece o SuccessSnackBar.

2024-02-18 23:27 UTC, eusoumabel approved these changes

2024-02-18 23:27 UTC, merged