acrescentada a versão na tela de login
Is-It-Safe/mobile pull request #457
Opened 2024-02-29 19:51 UTC by flaviomelodev

### O que foi feito? 
Adicionada a versão na tela de login

Ao entrar na tela de login vai aparecer a versão do app no rodapé

### Tipo de Mudança:

[x] feature

### Validações:

#### Testes Unitários:

- [ ] Meu código possui os devidos testes unitários

#### Layout:

- [ ] Não houveram mudanças nas telas
- [ ] Necessita de validação de Design

### Screenshots

2024-02-29 23:05 UTC, eusoumabel requested changes

2024-02-29 23:05 UTC, eusoumabel commented on lib/src/app/modules/auth/modules/login/presenter/widgets/show_version_application.dart
> +class ShowVersionApplication extends StatefulWidget {
Acho que esse nome não é muito claro. Deixa a entender que é um 'bool' e não um widget.

Sugestão de nome: SafeVersionAppWidget

2024-02-29 23:05 UTC, eusoumabel commented on lib/src/app/modules/auth/modules/login/presenter/widgets/show_version_application.dart
> +    setState(() {
SetState não deve ser utilizado.

2024-02-29 23:05 UTC, eusoumabel commented on lib/src/app/modules/auth/modules/login/presenter/widgets/show_version_application.dart
> +      Text('Versão do app: ${_packageInfo.version}', style: TextStyles.emotionalStatus());
Esse texto deveria estar no Intl.

2024-03-01 18:22 UTC, flaviomelodev commented on lib/src/app/modules/auth/modules/login/presenter/widgets/show_version_application.dart
> +class ShowVersionApplication extends StatefulWidget {
alterado para o nome sugerido.

2024-03-01 18:23 UTC, flaviomelodev commented on lib/src/app/modules/auth/modules/login/presenter/widgets/show_version_application.dart
> +    setState(() {
retirado o setState e utilizado o Bloc e SafeBuilder.

2024-03-01 18:23 UTC, flaviomelodev commented on lib/src/app/modules/auth/modules/login/presenter/widgets/show_version_application.dart
> +      Text('Versão do app: ${_packageInfo.version}', style: TextStyles.emotionalStatus());
Colocado no intl o texto "Versão do app: "

2024-03-02 04:38 UTC, eusoumabel commented on lib/src/app/modules/auth/modules/login/presenter/widgets/show_version_application.dart
> +class ShowVersionApplication extends StatefulWidget {
O nome não foi alterado..

2024-03-02 13:17 UTC, flaviomelodev commented
Feita a troca do nome do widget.

2024-03-02 17:30 UTC, eusoumabel approved these changes

2024-03-02 17:30 UTC, merged