Feat clipboard
Is-It-Safe/mobile pull request #52
Opened 2022-10-07 14:46 UTC by hastnumber1

Compartilhamento do nome do usuário da review.

Não pude fazer da data, porque não existe ainda.

2022-10-10 23:49 UTC, estermabel requested changes

2022-10-10 23:49 UTC, estermabel commented on lib/src/app/modules/profile/presenter/pages/profile_page.dart
> +                  name: snapshot.data!.data!.name!,
Ao invés de utilizar:
`name: snapshot.data!.data!.name!,`
utilizar:
`name: snapshot.data?.data?.name ?? StringConstants.empty,`

Importante utilizar o Null Safety sempre. Para não ocorrer erros de Crash por dado nulo que não está sendo tratado.

2022-10-10 23:49 UTC, estermabel commented on lib/src/app/modules/profile/presenter/widgets/profile_review.dart
> +    return result?.text ?? '';
Substituir o '' por StringConstants.empty

2022-10-10 23:49 UTC, estermabel commented on lib/src/app/modules/profile/presenter/widgets/profile_review.dart
> +//Classe para compartilhamento da review
Para a classe ser identificada como Documentação, colocar '///' ao invés de '//'.

'///' = Documentação

'//' = Comentário

2022-10-10 23:49 UTC, estermabel commented on lib/src/app/modules/profile/presenter/widgets/profile_review.dart
> +            ClipboardUtils.copy(widget.name);
O valor passado tá sendo somente o nome?


O formato deve ser "{Nome do Usuário}:  {Review feita pelo usuário}". Considerando que a data não está sendo passada pelo endpoint.

2022-10-11 13:31 UTC, hastnumber1 commented on lib/src/app/modules/profile/presenter/pages/profile_page.dart
> +                  name: snapshot.data!.data!.name!,
Alteração realizada como solicitado.

2022-10-11 13:31 UTC, hastnumber1 commented on lib/src/app/modules/profile/presenter/widgets/profile_review.dart
> +    return result?.text ?? '';
Alteração realizada como solicitado.

2022-10-11 13:31 UTC, hastnumber1 commented on lib/src/app/modules/profile/presenter/widgets/profile_review.dart
> +//Classe para compartilhamento da review
Alteração realizada como solicitado.

2022-10-11 13:32 UTC, hastnumber1 commented on lib/src/app/modules/profile/presenter/widgets/profile_review.dart
> +            ClipboardUtils.copy(widget.name);
Alteração realizada como solicitado.
Está passando o nome do usuário e a review que foi feita.

2022-10-11 13:32 UTC, hastnumber1 commented
Alterações solicitadas foram realizadas

2022-10-13 14:41 UTC, estermabel approved these changes

2022-10-13 14:41 UTC, merged