feat: create_safe_text_button
Is-It-Safe/mobile pull request #54
Opened 2022-10-17 15:12 UTC by hastnumber1

criei o componente safe_text_button.

Coloquei 2 onTap já que são dois textos clicáveis.

Pede para o editável do texto ser TextStyles.body, porém não existe. Então, usei o TextStyles.bodyText1.

2022-10-17 15:51 UTC, estermabel requested changes

2022-10-18 00:34 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +  void Function()? onTapPass;
Feita a alteração solicitada.

2022-10-18 00:35 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +        GestureDetector(
Feita a correção solicitada.

2022-10-18 00:38 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +        _secondText(context),
Feita a correção solicitada.

2022-10-18 01:03 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +          style: TextStyles.bodyText1(
Não consegui alterar com o código solicitado, mas sim de outra forma.

2022-10-18 01:03 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +            style: TextStyles.bodyText1(
Não consegui alterar com o código solicitado, mas sim de outra forma.

2022-10-18 01:03 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +        style: TextStyles.bodyText1(
Não consegui alterar com o código solicitado, mas sim de outra forma.

2022-10-18 11:42 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +          style: TextStyles.bodyText1(
Passando da forma solicitada aparece essa mensagem de erro: The argument type 'Object' can't be assigned to the parameter type 'TextStyle?'.

2022-10-18 11:42 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +            style: TextStyles.bodyText1(
Passando da forma solicitada aparece essa mensagem de erro: The argument type 'Object' can't be assigned to the parameter type 'TextStyle?'.

2022-10-18 11:42 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +        style: TextStyles.bodyText1(
Passando da forma solicitada aparece essa mensagem de erro: The argument type 'Object' can't be assigned to the parameter type 'TextStyle?'.

2022-10-18 11:43 UTC, hastnumber1 commented
Alterações solicitadas foram feitas, porém do style foi feita de outra forma.

2022-10-18 19:47 UTC, estermabel approved these changes

2022-10-18 19:48 UTC, merged