Safe place button
Is-It-Safe/mobile pull request #58
Opened 2022-10-21 12:31 UTC by hastnumber1

Criei o botão 'SafePlaceButton' com a snackbar, mas ao colocar '_mountEmptyCard()' no onEmpty ele não é retornado.

Coloquei no 'onCompleted' para teste e funcionou.

2022-10-24 19:56 UTC, estermabel requested changes

2022-10-24 19:56 UTC, estermabel commented on lib/src/app/modules/search/presenter/pages/search_page.dart
>            onEmpty: _mountEmptyCard(),
Esse pedaço de código não deveria ser modificado. As alterações deveriam ter sido feitas somente dentro do método _mountEmptyCard()

2022-10-24 19:56 UTC, estermabel commented on lib/src/components/widgets/safe_place_button.dart
> +              icon: const Icon(Icons.info),
O icon é definido automaticamente quando é passado o tipo do SafeSnackBar. Se preferir, pode remover.

2022-10-24 19:56 UTC, estermabel commented on lib/src/components/widgets/safe_place_button.dart
> +    return IconButton(
O widget que deveria ser utilizado é o SafeTextButton. Assim como está sendo exibido no design que a task faz referência.

[DESIGN](https://www.figma.com/file/d8fHoLCnNU3EDQg0UQQTPE/Is-It-Safe%3F?node-id=932%3A2000)

2022-10-24 19:56 UTC, estermabel commented on lib/src/app/modules/search/presenter/pages/search_page.dart
> +        //Funcionalidade disponível em breve
Remover comentários.

2022-10-24 19:56 UTC, estermabel commented on lib/src/app/modules/search/presenter/pages/search_page.dart
> +        const SafePlaceButton(),
Substituir pelo SafeTextButton.

o onTap exibe o SafeSnackBar
o pré-text e o text estão descritos no layout definido na task.

2022-10-24 20:37 UTC, estermabel requested changes

2022-10-24 20:37 UTC, estermabel commented on lib/src/app/modules/search/presenter/pages/search_page.dart
> +  final Function()? addButton;
Remover esta variável, não é necessária.

2022-10-24 21:59 UTC, hastnumber1 commented on lib/src/app/modules/search/presenter/pages/search_page.dart
>            onEmpty: _mountEmptyCard(),
Retornado para o código anterior => _mountResultList(.

2022-10-26 00:10 UTC, hastnumber1 commented on lib/src/components/widgets/safe_place_button.dart
> +              icon: const Icon(Icons.info),
Colocado no padrão que vem do SafeSnackBar.

2022-10-26 00:14 UTC, hastnumber1 commented
Ficaram algumas pendências que vejo com você amanhã de noite.

2022-10-26 00:14 UTC, hastnumber1 commented on lib/src/app/modules/search/presenter/pages/search_page.dart
> +  final Function()? addButton;
Variável removida.

2022-10-26 00:14 UTC, hastnumber1 commented on lib/src/app/modules/search/presenter/pages/search_page.dart
> +        const SafePlaceButton(),
Deletado o SafePlaceButton e colocado o SafeTextButton e o onTap exibe a SafeSnackBar

2022-10-26 00:14 UTC, hastnumber1 commented on lib/src/app/modules/search/presenter/pages/search_page.dart
> +        //Funcionalidade disponível em breve
Comentários removidos

2022-10-26 00:14 UTC, hastnumber1 commented on lib/src/components/widgets/safe_place_button.dart
> +    return IconButton(
Corrigido e utilizado SafeTextButton

2022-10-26 10:26 UTC, estermabel requested changes

2022-10-26 10:26 UTC, estermabel commented on lib/src/app/modules/search/presenter/pages/search_page.dart
> +          text: ' Crie ele aqui.',
Os textos deves ser declarados dentro do INTL

e o preText é: 'Não encontrou o local que estava procurando? '. Não há necessidade do posText.

2022-10-26 10:26 UTC, estermabel commented on lib/src/components/widgets/safe_text_button.dart
> +        ),
Por que foi feita uma alteração nessa classe? O widget estava pronto para uso.

2022-10-27 01:57 UTC, hastnumber1 commented on lib/src/app/modules/search/presenter/pages/search_page.dart
> +          text: ' Crie ele aqui.',
Corrigido.

2022-10-27 01:57 UTC, hastnumber1 commented on lib/src/components/widgets/safe_text_button.dart
> +        ),
Corrigido.

2022-10-27 01:59 UTC, hastnumber1 commented
Implementei com o Text.rich() e apresentou o comportamento esperado.

2022-10-31 12:37 UTC, estermabel approved these changes

2022-10-31 12:38 UTC, merged