# [Serviço][Home] Mapear Endpoint de GetBestRatedPlaces
Is-It-Safe/mobile pull request #59
Opened 2022-10-22 01:06 UTC by Endleyson

criação:
- get_rated_places_use_case;
- criação response_get_rated_places;
modificado:
-  string_constants;
- location_entity;
- api_constants;
- location_services;
- location_services_interface
- shared_preference_service;
- shared_preference_service_interface

2022-10-24 20:46 UTC, estermabel requested changes

2022-10-24 20:46 UTC, estermabel commented on lib/src/service/shared_preferences/shared_preferences_service_interface.dart
> +  Future<String> readPlaces();
Criar um método savePlace e transformar o readPlaces no singular (readPlace), é somente 1 local que é salvo.

2022-10-25 11:53 UTC, Endleyson commented on lib/src/service/shared_preferences/shared_preferences_service_interface.dart
> +  Future<String> readPlaces();
ajustes realizados

2022-10-25 14:07 UTC, estermabel requested changes

2022-10-25 14:07 UTC, estermabel commented on lib/src/service/shared_preferences/shared_preferences_service.dart
> +    prefs.setString(StringConstants.place, value);
A chave não deve ser declarada na classe de StringConstants, mas sim na classe de KeyConstants

2022-10-26 10:21 UTC, estermabel approved these changes

2022-10-26 10:21 UTC, merged