confirm_password
Is-It-Safe/mobile pull request #64
Opened 2022-10-29 15:12 UTC by Endleyson

2022-10-31 13:59 UTC, estermabel requested changes

2022-10-31 13:59 UTC, estermabel commented on lib/src/domain/use_case/confirm_password_use_case.dart
> +class GetBestRatedPlacesUseCase extends SafeUseCase {
Nome da classe não corresponde à sua funcionalidade

2022-10-31 16:39 UTC, Endleyson commented on lib/src/domain/use_case/confirm_password_use_case.dart
> +class GetBestRatedPlacesUseCase extends SafeUseCase {
Realizado a correção do nome da classe

2022-11-01 21:52 UTC, estermabel approved these changes

2022-11-01 21:52 UTC, merged