Implementação para classe de localização.
Is-It-Safe/mobile pull request #65
Opened 2022-11-01 01:03 UTC by NETfellow

MR contendo implementação para classe responsável pela localização do usuário.

Libs utilizadas: [geolocator](https://pub.dev/packages/geolocator), [geocoding](https://pub.dev/packages/geocoding).

Em caso de erro implementei também a chamada para a [API ViaCep](https://viacep.com.br/) que pode ser utilizada como "plano B" caso ocorra do geocoding trazer informações incompletas (um risco real para cidades do anterior).

2022-11-01 23:44 UTC, estermabel requested changes

2022-11-01 23:44 UTC, estermabel commented on lib/src/app/modules/home/presenter/bloc/home_bloc.dart
> +  ValueNotifier<Placemark?> currentLocation = ValueNotifier(null);
Porque o uso do value notifier e não do StreamController???

2022-11-01 23:44 UTC, estermabel commented on lib/src/app/modules/home/presenter/pages/home_page.dart
> +              // if (tab == 0) controller.getClosePlacesLocations();
Captura da localização do usuário deve ser feita sempre que ele acessa a tab 0

2022-11-01 23:44 UTC, estermabel commented on lib/src/components/location/safe_locator.dart
> +class SafeLocatorImpl implements SafeLocatorContract {
Ajustar nomenclatura de acordo com a [documentação](https://docs.isitsafe.com.br/docs/desenvolvimento/mobile/padroes_de_desenvolvimento/classes/#interfaces)

2022-11-01 23:44 UTC, estermabel commented on lib/src/components/widgets/safe_app_bar.dart
> +  final Function()? onLogoIconTap;
Remover Function, não deveria precisar ser utilizada

2022-11-01 23:44 UTC, estermabel commented on lib/src/core/interfaces/safe_locator.dart
> +abstract class SafeLocatorContract {
Ajustar nomenclatura de acordo com a [documentação](https://docs.isitsafe.com.br/docs/desenvolvimento/mobile/padroes_de_desenvolvimento/classes/#interfaces)

2022-11-02 00:33 UTC, NETfellow commented on lib/src/app/modules/home/presenter/bloc/home_bloc.dart
> +  ValueNotifier<Placemark?> currentLocation = ValueNotifier(null);
Foi apenas para termos um teste na mão.

Imaginei que iriamos implementar a visualização da localização de outra forma e por isso não quis implementar de uma forma mais envolvida.

2022-11-02 00:33 UTC, NETfellow commented on lib/src/app/modules/home/presenter/pages/home_page.dart
> +              // if (tab == 0) controller.getClosePlacesLocations();
Combinado!

2022-11-02 00:40 UTC, NETfellow commented on lib/src/components/widgets/safe_app_bar.dart
> +  final Function()? onLogoIconTap;
Combinado! Meio que sempre foi o plano remover essa função uma vez que implementei só para testes.

2022-11-02 21:09 UTC, estermabel approved these changes

2022-11-02 21:10 UTC, merged