[Profile] Implementar ação de deletar review do usuário
Is-It-Safe/mobile pull request #67
Opened 2022-11-09 02:53 UTC by devlucasandrade

Arquivos editados
- intl:  com a criação de um textError para a review
- profile_bloc: para a função deleteReview e correção no dispose
- profile_page:  com a função para receber o id e retornar sucesso ou falha ao usuário
- profile_module: para a injeção de dependência
- delete_review_use_case: para correção na variável _service

2022-11-09 12:16 UTC, estermabel requested changes

2022-11-09 12:16 UTC, estermabel commented on lib/src/app/modules/profile/presenter/bloc/profile_bloc.dart
> +  Future<bool> deleteReview({required int id}) async {
Especificar qual id é para ser passado.

ex: idReview, idUser, ...

2022-11-09 12:16 UTC, estermabel commented on lib/src/app/modules/profile/presenter/pages/profile_page.dart
> +                      final id = reviews![index].id;
Não utilizar a "!"a menos que você verifique antecipadamente que o objeto é != null. 

A implementação atual pode acabar disparando uma exception de "null check on a null value".

O ideal é utilizar o "?".

final int? id = reviews?[index].id;

A controller deve receber um id tipo int?, assim como a use_case. Na camada de domain (use_case), que fazemos o tratamento sobre o que será passado para o service.

2022-11-09 12:16 UTC, estermabel commented on lib/src/domain/use_case/delete_review_use_case.dart
>    Future<String> call(int idReview) async {
Colocar o call com parâmetros nomeados e o tipo do idReview como int?

Verifica se o idReview é != null. Caso sim, faz a chamada normal do service. Caso não, retorna uma String "Erro ao deletar a review, tente novamente em alguns instantes!"

2022-11-09 12:16 UTC, estermabel commented on lib/src/app/modules/profile/presenter/pages/profile_page.dart
> +                              message: S.current.textDefaultDeleteReviewMessage,
Exibir a mensagem que é retornada do BLoC.

2022-11-09 23:43 UTC, devlucasandrade commented
Correções realizadas.

2022-11-14 18:48 UTC, estermabel approved these changes

2022-11-14 18:48 UTC, merged