feat: mapear serviço de deletar usuário
Is-It-Safe/mobile pull request #69
Opened 2022-11-10 01:58 UTC by hastnumber1

2022-11-14 18:54 UTC, estermabel requested changes

2022-11-14 18:54 UTC, estermabel commented on lib/src/domain/use_case/delete_use_case.dart
> +class DeleteUseCase extends SafeUseCase {
Nome não está muito claro. 'Delete' oq??

sugestão: DeleteUserUseCase

2022-11-14 18:54 UTC, estermabel commented on lib/src/domain/use_case/delete_use_case.dart
> +  Future<String> call(int idUser) async {
[Os parâmetros devem ser nomeados.](https://docs.isitsafe.com.br/docs/desenvolvimento/mobile/padroes_de_desenvolvimento/metodos#métodos-com-parâmetros)

2022-11-14 18:54 UTC, estermabel commented on lib/src/service/api/modules/profile/profile_service.dart
> +  Future<ResponseDeleteUser> deleteUser(int idUser) async {
[Os parâmetros devem ser nomeados.](https://docs.isitsafe.com.br/docs/desenvolvimento/mobile/padroes_de_desenvolvimento/metodos#métodos-com-parâmetros)

2022-11-14 18:54 UTC, estermabel commented on lib/src/service/api/modules/profile/request/request_delete_user.dart
> +}
Classe não utilizada, deletar

2022-11-14 18:54 UTC, estermabel commented on lib/src/service/api/modules/profile/response/response_delete_user.dart
> +// ignore_for_file: public_member_api_docs, sort_constructors_first
Remover comentário

2022-11-14 18:54 UTC, estermabel commented on lib/src/service/api/modules/profile/response/response_delete_user.dart
> +  }
Classe de response não possui o toJson

2022-11-14 18:54 UTC, estermabel commented on lib/src/service/api/modules/profile/response/response_delete_user.dart
> +  }
Classe de request, o método .fromJson deve ser um factory de acordo com o [exemplo](https://docs.isitsafe.com.br/docs/desenvolvimento/mobile/padroes_de_desenvolvimento/classes#response).

2022-11-15 00:21 UTC, hastnumber1 commented on lib/src/service/api/modules/profile/response/response_delete_user.dart
> +  }
Criada a factory

2022-11-15 00:21 UTC, hastnumber1 commented on lib/src/domain/use_case/delete_use_case.dart
> +class DeleteUseCase extends SafeUseCase {
Nome alterado

2022-11-15 00:21 UTC, hastnumber1 commented on lib/src/domain/use_case/delete_use_case.dart
> +  Future<String> call(int idUser) async {
Alterado para parâmetros nomeados.

2022-11-15 00:21 UTC, hastnumber1 commented on lib/src/service/api/modules/profile/profile_service.dart
> +  Future<ResponseDeleteUser> deleteUser(int idUser) async {
Alterado para parâmetros nomeados.

2022-11-15 00:21 UTC, hastnumber1 commented on lib/src/service/api/modules/profile/request/request_delete_user.dart
> +}
Classe deletada

2022-11-15 00:21 UTC, hastnumber1 commented on lib/src/service/api/modules/profile/response/response_delete_user.dart
> +// ignore_for_file: public_member_api_docs, sort_constructors_first
Comentário removido

2022-11-15 00:21 UTC, hastnumber1 commented on lib/src/service/api/modules/profile/response/response_delete_user.dart
> +  }
Classe deletada

2022-11-15 00:22 UTC, hastnumber1 commented
Alterações solicitadas foram realizadas

2022-11-15 13:46 UTC, estermabel submitted a review, later dismissed

2022-11-19 17:31 UTC, hastnumber1 commented
Conflitos resolvidos

2022-11-21 22:56 UTC, merged