feature/cards de impressao
Is-It-Safe/mobile pull request #84
Opened 2022-12-21 17:56 UTC by hastnumber1

Cards de impressão criados, mas as imagens svg ficaram brancas

2022-12-22 23:23 UTC, estermabel requested changes

2022-12-22 23:23 UTC, estermabel commented on lib/l10n/intl_pt.arb
> +    "textSuccessCard3":"para comunidade LGBTQIA+",
Esse texto pode ser uma única variável. O nome das variáveis deve corresponder ao texto.

Por exemplo: textMostPeopleSafePlace

2022-12-22 23:23 UTC, estermabel commented on lib/l10n/intl_pt.arb
> +    "textAlertCard3":"associados a esse local para",
Esse texto pode ser uma única variável. O nome das variáveis deve corresponder ao texto.

Por exemplo: textMostPeopleAlertPlace

2022-12-22 23:23 UTC, estermabel commented on lib/l10n/intl_pt.arb
> +    "textErrorCard3":"considera esse local seguro",
Esse texto pode ser uma única variável. O nome das variáveis deve corresponder ao texto.

Por exemplo: textMostPeopleDangerPlace

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +enum Cards {
Nome muito generalizado. Ao criar uma enumeração para um componente, é importante especificar que é uma enumeração exclusiva para o componente.

Sugestão: SafeImpressionEnum

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +}
A enumeração deveria estar sendo passada por parâmetro, se não, não há como determinar o card que será exibido.

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +    double width = 344;
Na maioria dos casos é tranquilo definir altura para componentes, quando o scroll é vertical. Mas a largura raramente deve ser fixa por conta da responsividade.

Se houver um usuário caso a tela seja menor do que 344 em largura, o componente vai dar overflow.

Substituir a largura pelo uso do MediaQuery.

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +    Cards card = Cards.error;
Deveria estar sendo passado por parâmetro

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +  );
Esses 3 métodos são completamente idênticos. É preciso reestruturar para que não ocorra replicação de código

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +          child: SizedBox(
Pq utilizar um SizedBox aqui, se no método ha um container com mesma altura e largura??

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +    width: 344,
Utilizar MediaQuery para largura e, porque não foi utilizado os parâmetros que você declarou no começo da classe, já que são os mesmos??

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +        ),
Ao reduzir as variáveis de texto para 1 so ao invés de 3, o widget de Text será suficiente para exibi-lo em tela

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +        ),
O SVG do arco-iris poderia ter sido exportado como um conjunto, ao invés de 4 arquivos separados. Se precisar de auxílio com isso, só sinalizar que te encaminho o arquivo.

Os SVGs já estão declarados na classe AssetConstants:

- AssetConstants.impression.safe
- AssetConstants.impression.warning
- AssetConstants.impression.danger

2022-12-22 23:23 UTC, estermabel commented on lib/src/components/widgets/safe_impression_card.dart
> +              child: SvgPicture.asset('images/modules/review/vector1.svg'),
Todos os caminhos de assets devem ser declarados na classe AssetConstants. Inclusive, os assets utilizados nessa task se encontram la: 
- AssetConstants.impression.safe
- AssetConstants.impression.warning
- AssetConstants.impression.danger

2022-12-24 09:34 UTC, hastnumber1 commented on lib/l10n/intl_pt.arb
> +    "textAlertCard3":"associados a esse local para",
alterações realizadas

2022-12-24 09:34 UTC, hastnumber1 commented on lib/l10n/intl_pt.arb
> +    "textErrorCard3":"considera esse local seguro",
alterações realizadas

2022-12-24 09:36 UTC, hastnumber1 commented on lib/src/components/widgets/safe_impression_card.dart
> +enum Cards {
Alterações realizadas

2022-12-24 09:39 UTC, hastnumber1 commented on lib/src/components/widgets/safe_impression_card.dart
> +          child: SizedBox(
Alteração realizada

2022-12-24 09:42 UTC, hastnumber1 commented on lib/src/components/widgets/safe_impression_card.dart
> +        ),
Alteração realizada

2022-12-24 10:39 UTC, hastnumber1 commented on lib/src/components/widgets/safe_impression_card.dart
> +              child: SvgPicture.asset('images/modules/review/vector1.svg'),
Corrigido

2022-12-24 10:39 UTC, hastnumber1 commented on lib/src/components/widgets/safe_impression_card.dart
> +        ),
Corrigido

2022-12-24 10:40 UTC, hastnumber1 commented on lib/l10n/intl_pt.arb
> +    "textSuccessCard3":"para comunidade LGBTQIA+",
alterações realizadas

2022-12-24 17:21 UTC, hastnumber1 commented on lib/src/components/widgets/safe_impression_card.dart
> +}
Corrigido

2022-12-29 19:15 UTC, hastnumber1 commented on lib/src/components/widgets/safe_impression_card.dart
> +    width: 344,
resolvido

2022-12-30 00:41 UTC, estermabel submitted a review, later dismissed

2022-12-30 12:18 UTC, estermabel approved these changes

2022-12-30 12:19 UTC, merged