Bugfix/register-page
Is-It-Safe/mobile pull request #86
Opened 2022-12-22 20:12 UTC by feliperfdev

-> Título do SafeDialog agora está ajustável à tela baseado no MediaQuery
-> HelperFunctions convertidas para StatelessWigets visando manter os estados persistirem com suas alterações -> Lógica do `isAdvanceButton` corrigida

2022-12-22 23:28 UTC, estermabel requested changes

2022-12-22 23:28 UTC, estermabel commented on lib/src/app/modules/auth/register/presenter/bloc/register_bloc.dart
> +      // gendersController.sink.add(SafeEvent.error(e.toString())); /// [Deprecated]
Apagar comentário

2022-12-22 23:28 UTC, estermabel commented on lib/src/app/modules/auth/register/presenter/bloc/register_bloc.dart
> +      // sexualOrientationsController.sink.add(SafeEvent.error(e.toString())); /// [Deprecated]
Apagar comentário

2022-12-22 23:28 UTC, estermabel commented on lib/src/app/modules/auth/register/presenter/bloc/register_bloc.dart
> +      // doRegisterController.sink.add(SafeEvent.error(e.toString())); /// [Deprecated]
Apagar comentário

2022-12-22 23:28 UTC, estermabel commented on lib/src/app/modules/auth/register/presenter/pages/register_page.dart
> +  final controller = Modular.get<RegisterBloc>();
Porque a modificação?

2022-12-22 23:28 UTC, estermabel commented on lib/src/app/modules/auth/register/presenter/pages/register_profile_page.dart
> +  final controller = Modular.get<RegisterBloc>();
Pq a modificação??

2022-12-22 23:28 UTC, estermabel commented on lib/src/app/modules/auth/register/presenter/widgets/stream_safe_dropdown.dart
> +  final bool isGenderDropdownExpanded;
nome de variável muito específico. Talvez tirar a palavra 'Gender' deixe 100% rsrs

2022-12-23 00:36 UTC, feliperfdev commented on lib/src/app/modules/auth/register/presenter/pages/register_page.dart
> +  final controller = Modular.get<RegisterBloc>();
Há algum tempo o `ModularState` se tornou depreciado (esta mensagem é informada como aviso no próprio código, pedindo para usar o `Modular.get()` ao invés dessa forma).

A equipe do Modular há um tempo mergeou um PR onde há um aviso sobre o uso do `ModularState`, explicando o motivo de ter sido depreciado e o que estava causando ao código. [Issue referente](https://github.com/Flutterando/modular/pull/693).

2022-12-29 18:46 UTC, feliperfdev commented on lib/src/app/modules/auth/register/presenter/bloc/register_bloc.dart
> +      // gendersController.sink.add(SafeEvent.error(e.toString())); /// [Deprecated]
Corrigido

2022-12-29 18:46 UTC, feliperfdev commented on lib/src/app/modules/auth/register/presenter/bloc/register_bloc.dart
> +      // sexualOrientationsController.sink.add(SafeEvent.error(e.toString())); /// [Deprecated]
Corrigiddo

2022-12-29 18:47 UTC, feliperfdev commented on lib/src/app/modules/auth/register/presenter/bloc/register_bloc.dart
> +      // doRegisterController.sink.add(SafeEvent.error(e.toString())); /// [Deprecated]
Corrigido

2022-12-30 00:38 UTC, estermabel approved these changes

2022-12-30 00:39 UTC, merged